# Hyper parameter Optimization using a Particle Swarm Approach for neural networks

In [42]:
import random
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.datasets import mnist
import tensorflow as tf
from tensorflow.keras.utils import to_categorical

In [43]:
class Particle:
  def __init__(self, bounds, dimensions):
    self.position = [random.uniform(bound[0], bound[1]) for bound in bounds]
    self.velocity = [0.0 for _ in range(dimensions)]
    self.pbest = self.position  # Personal best position
    self.pbest_fitness = float('inf')  # Personal best fitness (initialize to high value)

def fitness_function(hyperparameters):
  # Unpack hyperparameters
  learning_rate, hidden_units = hyperparameters

  # Load MNIST dataset
  (X_train, y_train), (X_test, y_test) = mnist.load_data()
  X_train = X_train.reshape(X_train.shape[0], 784)  # Flatten images
  X_test = X_test.reshape(X_test.shape[0], 784)
  X_train = X_train / 255.0  # Normalize pixel values
  print('the shape of the data:', X_train.shape)
  print('the shape of the Labels:', y_train.shape) 
  print(y_train)
  # One-hot encode labels
  #y_train_encoded = to_categorical(y_train)

  # Build model based on hyperparameters
  model = Sequential([
    Dense(hidden_units, activation='relu', input_shape=(784,)),
    Dense(10, activation='softmax')  # 10 output units for digits 0-9
  ])
    
  model.compile(loss='sparse_categorical_crossentropy', optimizer=tf.keras.optimizers.Adam(
    learning_rate=learning_rate))

  # Train the model (using a small number of epochs for efficiency)
  model.fit(X_train, y_train, epochs=3, batch_size=100)

  # Evaluate the model on test data
  loss  = model.evaluate(X_test, y_test)
  return loss  # Lower loss indicates better performance

def particle_swarm_optimization(bounds, dimensions, swarm_size, max_iterations, inertia=0.72):
  swarm = [Particle(bounds, dimensions) for _ in range(swarm_size)]

  for i in range(max_iterations):
    for particle in swarm:
      # Evaluate current position
      fitness = fitness_function(particle.position)
      # Update personal best
      if fitness < particle.pbest_fitness:
        particle.pbest = particle.position
        particle.pbest_fitness = fitness

      # Find global best
      global_best = min(swarm, key=lambda p: p.pbest_fitness)

      # Update velocity
      for j in range(dimensions):
        cognitive = random.random() * (particle.pbest[j] - particle.position[j])
        social = random.random() * (global_best.pbest[j] - particle.position[j])
        particle.velocity[j] = inertia * particle.velocity[j] + cognitive + social

      # Update position
      for j in range(dimensions):
        particle.position[j] = max(bounds[j][0], min(bounds[j][1], particle.position[j] + particle.velocity[j]))

  # Return the particle with the best fitness
  return min(swarm, key=lambda p: p.pbest_fitness)

In [44]:
# Example usage

bounds = [
  [0.001, 0.1],  # Learning rate (remains float)
  
  [32, 64, 128, 256],  # Discrete list of hidden units (integers)
]

In [45]:
dimensions = len(bounds)
swarm_size = 20
max_iterations = 50

In [46]:
best_particle = particle_swarm_optimization(bounds, dimensions, swarm_size, max_iterations)

the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3998
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.3238
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 66.9152
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.4948
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.3758
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 66.3980
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2885
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1406
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 16.7936
the shape of 

313/313 [==============================] - 1s 2ms/step - loss: 57.0933
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3905
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.3188
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 55.7379
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3123
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1582
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 17.9493
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.4209
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.2177
Epoch 3/3
313/313 [====

313/313 [==============================] - 1s 2ms/step - loss: 19.8896
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2923
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1480
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 22.9738
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.4285
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.2244
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 24.9122
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.4097
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.2075
Epoch 3/3
313/313 [====

Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2963
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1417
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 17.4141
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.4317
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.2111
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 21.6434
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.4211
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.2270
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 27.5814
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600

Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3141
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1600
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 20.9268
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.4226
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.2264
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 25.3205
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.4293
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.2178
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 21.4580
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600

Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.4233
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.2144
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 23.2681
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3382
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1723
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 20.4674
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2973
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1474
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 20.3157
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600

Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2906
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1383
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 20.8617
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2879
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1407
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 19.1262
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2790
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1472
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 22.9181
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600

Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2825
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1390
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 19.6626
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3081
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1556
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 19.7782
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3220
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1738
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 23.9987
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600

Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2719
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1318
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 19.8273
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2991
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1533
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 19.9191
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2786
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1423
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 19.8974
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600

Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2711
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1335
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 19.8709
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2964
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1496
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 21.1053
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2703
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1424
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 18.6048
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600

Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2778
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1371
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 20.0146
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2729
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1347
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 17.6215
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2888
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1413
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 20.3200
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600

Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3065
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1521
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 17.5376
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2796
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1357
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 18.3219
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2763
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1338
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 16.9670
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600

Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2818
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1380
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 19.7305
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2915
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1449
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 17.5508
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2788
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1421
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 18.3921
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600

Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2665
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1332
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 19.4160
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2688
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1317
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 21.0358
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2954
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1390
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 17.9425
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600

Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2733
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1392
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 19.4131
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2691
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1310
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 19.2746
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2710
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1278
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 20.9941
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600

Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2762
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1355
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 17.0373
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2938
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1435
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 18.4425
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2789
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1302
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 18.1139
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600

Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2937
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1460
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 16.1131
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3027
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1467
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 17.5836
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2897
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1432
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 17.0598
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600

Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3162
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1523
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 18.0334
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3317
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1616
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 19.8058
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3416
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1705
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 19.2582
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600

Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3246
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1556
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 18.5791
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3244
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1584
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 17.1705
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3359
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1688
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 18.7244
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600

Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3127
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1520
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 16.6082
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.2979
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1492
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 18.7457
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3359
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1600
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 18.8244
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600

Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3605
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1760
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 15.6449
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3580
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1869
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 21.6075
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3485
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1723
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 17.9279
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600

Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3513
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1761
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 18.7228
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3409
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1606
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 15.7659
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3461
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1725
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 17.3778
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600

Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3449
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1698
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 19.8252
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3347
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1629
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 18.1736
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3548
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1759
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 18.5744
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600

Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3366
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1714
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 17.4734
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3571
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1765
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 18.2018
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3413
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1614
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 20.0609
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600

Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3474
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1729
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 19.2335
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3463
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1676
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 16.6806
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3546
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1758
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 18.9873
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600

In [47]:
print("Best hyperparameters:", best_particle.pbest)
print("Test accuracy with best hyperparameters:", fitness_function(best_particle.pbest))

Best hyperparameters: [0.0016930908254939286, 52.69150029829337]
the shape of the data: (60000, 784)
the shape of the Labels: (60000,)
[5 0 4 ... 5 6 8]
Epoch 1/3
600/600 [==============================] - 2s 2ms/step - loss: 0.3542
Epoch 2/3
600/600 [==============================] - 1s 2ms/step - loss: 0.1705
Epoch 3/3
313/313 [==============================] - 1s 2ms/step - loss: 16.4967
Test accuracy with best hyperparameters: 16.496742248535156
